In [4]:
# %load D:\Noven\python work\ML100Days\D02.py
import numpy as np



#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
array1 = np.array(range(30))
# print(array1)
# print(array1.reshape(5,6))
reshape_array1 = array1.reshape(5,6,order="F")
print(reshape_array1)




#2.呈上題的array，找出被6除餘1的數的索引

# print(np.where(array1.reshape(5,6)%6==1))
print(np.where(reshape_array1%6==1))


[[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]]
(array([0, 1, 2, 3, 4], dtype=int64), array([5, 0, 1, 2, 3], dtype=int64))
